PUT http://localhost:3003/api/blogs/6a32706ed674a38e8b4227cb
Content-Type: application/json

{
    "title": "Reactin alkeet",
    "author": "Matti Muukalainen",
    "url": "https://react.dev",
    "likes": 30
}