POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmFhIiwiaWQiOiI2YTllOGUxNjczYzA1NjhhYjdiNTgyOWUiLCJpYXQiOjE3ODg3ODI3MTd9.d4XDOJnOAGVpVR9a73duxgmmhrqMnTudFWHf5y-OjI0

{
    "title": "Reactin perusteet",
    "author": "Matti Meikäläinen",
    "url": "https://react.dev",
    "likes": 30,
    "userId": "6a9e6c2ae99dc581f620ec76"
}